### ISSUE TITLE
Inserir plano de apoio no site 

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#10]
Inserir link para plano de apoio em https://2022.pythonbrasil.org.br/programa-auxilio-financeiro

Imagino que uma localização onteressante é ao lado do botão de submissão.

Plano: https://www.canva.com/design/DAFJmcSHEL8/xIJW94m3geO31p2Q_eHLhA/edit?utm_content=DAFJmcSHEL8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by alynnefs** [comment]
pull request feito: https://github.com/pythonbrasil/pybr2022-site/pull/100
