### ISSUE TITLE
Escolher hotel para hospedagem

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#14]
Entrar em contato com hotéis e negociar reserva de um grupo de 21 pessoas, sendo:

Total Pessoas: 21
Total habitação: 11

Distribuição:
5 habitacoes entre 16 e 23/10 - 7 diárias
3 habitacoes entre 17 e 23/10 - 6 diarias
3 habitacoes entre 19 e 23/10 - 4 diarias

**Comment by cecivieira** [comment]
Hoteis sugeridos pela organizaçao da pybr2022:

Hotel Adrianópolis – reservasadrianopolis@manaushoteis.tur.br
Hotel Millennium – reservasmillennium@manaushoteis.tur.br
Hotel Saint Paul – reservassaintpaul@manaushoteis.tur.br
Hotel Express Vieiralves – reservasexpress@manaushoteis.tur.br

**Comment by cecivieira** [comment]
Massa @lipemorais !!
Tu poderia verificar com o Ibis Budget também (https://g.page/ibis-budget-manaus?share)?

**Comment by lipemorais** [comment]
Em uma consulta rápida pelo telefone eles mencionaram que a tarifa de balcão seria 212* 2% = 216,24 por dia + 29,00 de café da manhã por pessoal. Assim ficaria 216,24 + 2*29 café da manhã = 274,24 por dia. 

**Para conseguir uma tarifa melhor, ele recomendou mandar um e-mail para a central de reservas** em [h7016-re1@accor.com](mailto:h7016-re1@accor.com)

Mandei o e-mail para o Ibis Budget pelo Freshdesk
[https://pythonbrasil.freshdesk.com/a/tickets/8734](https://pythonbrasil.freshdesk.com/a/tickets/8734)

**Comment by maribedran** [comment]
Tem esse hostel também que daria pra fechar quartos inteiros só pra gente: https://www.booking.com/hotel/br/vila-hostel-manaus.pt-br.html?aid=356937&label=metagha-link-MRBR-hotel-6443196_dev-desktop_los-7_bw-41_dow-Sunday_defdate-0_room-0_gstadt-2_rateid-0_aud-0_gacid-6623578791_mcid-10_ppa-0_clrid-0_ad-1_gstkid-0_checkin-20221016__lp-1001625_r-714171512794499101&sid=9b65a6ce50e78b6ee30e76720dc47008&all_sr_blocks=644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319604_349036123_1_0_0;checkin=2022-10-16;checkout=2022-10-23;dest_id=-653186;dest_type=city;dist=0;group_adults=21;group_children=0;hapos=1;highlighted_blocks=644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319603_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319601_349036123_1_0_0%2C644319604_349036123_1_0_0;hpos=1;matching_block_id=644319603_349036123_1_0_0;no_rooms=2;req_adults=21;req_children=0;room1=A%2CA%2CA%2CA%2CA%2CA%2CA%2CA%2CA%2CA;room2=A%2CA%2CA%2CA%2CA%2CA%2CA%2CA%2CA%2CA%2CA;sb_price_type=total;sr_order=popularity;sr_pri_blocks=644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319603_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319601_349036123_1_0_0__38563%2C644319604_349036123_1_0_0__44492;srepoch=1662383702;srpvid=da3f5d2a8c9a00cb;type=total;ucfs=1&#hotelTmpl

**Comment by cecivieira** [comment]
@maribedran o link remete para uma lista. Tu se refere a algum hostel específico? Quantas pessoas por quanto tu acha que é viável pra gente?

**Comment by lipemorais** [comment]
@cecivieira  seria o primeiro gostei da lista. Esse aqui 
![BEBDA3DF-10FC-4AC7-99E7-EA67C8CDE61C](https://user-images.githubusercontent.com/5021565/188858160-184a501d-4e5e-4006-9f97-9b66aacc2d1c.png)
Mas achei o preço salgado, 8158 reais

**Comment by maribedran** [comment]
Isso é o valor total pra 21 pessoas por 7 noites pelo que eu entendi. Dá 55 por pessoa a diária.

**Comment by cecivieira** [comment]
A estrutura desse hostel (Vila hostel) é:

18 camas - masculino 01
04 camas - masculino 02
14 camas - feminino 01
04 camas - feminino 02

Temos 19 mulheres beneficiadas e 2 homens.
Vocês acham de boa fechar os quartos com as mulheres do evento (faltaria alocar 1) e os homens colocar no quarto de 4 camas?

**Comment by maribedran** [comment]
Acho que vale até perguntar se fechando uma reserva grande eles conseguem colocar todo mundo do evento junto, por exemplo deixando esse quarto de 4 pros dois homens e mais duas mulheres. Até porque quando a gente fechar essa primeira leva de reservas deve sobrar dinheiro e vai dar pra chamar mais homens da lista.

**Comment by maribedran** [comment]
Mandei mensagem pra eles.

**Comment by cecivieira** [comment]
O hostel informou que tem disponibilidade para reserva de dois quartos completos: 18 camas e 4 camas, no período de 16 a 23 de outubro.

Aguardando orçamento par conclusão da compra.

**Comment by cecivieira** [comment]
Valor da hospedagem para 21 pessoas no período de 16 a 23 de outubro no Vila Hostel Manaus:

R$ 8.500,00 a vista via PIX, DINHEIRO e DEBITO.
