### ISSUE TITLE
Compra de passagem aérea

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#15]
Edit:
Cotação e compra de passagens aéreas

Planilha com dados dos voos:
https://docs.google.com/spreadsheets/d/10l7u6zfwO0CBuRxlq1wxFYn7Namuv0WfdlOuGozvtWo/edit#gid=0
------------------------------------------
Pesquisar compra de passagem aérea REEMBOLSAVEIS por grupo:

ida | volta | origem | destino | restricao horaria para viagem | total_passagens
-- | -- | -- | -- | -- | --
16/10/2022 | 23/10/2022 | recife | manaus | No dia 16/10 chegar em Manaus a partir das 9:00. No dia 23/10 saída a partir das 19:00 | 1
16/10/2022 | 23/10/2022 | guarulhos | manaus | No dia 16/10 chegar em Manaus a partir das 9:00. No dia 23/10 saída a partir das 19:00 | 2
16/10/2022 | 23/10/2022 | joao pessoa | manaus | No dia 16/10 chegar em Manaus a partir das 9:00. No dia 23/10 saída a partir das 19:00 | 2
16/10/2022 | 23/10/2022 | porto alegre | manaus | No dia 16/10 chegar em Manaus a partir das 9:00. No dia 23/10 saída a partir das 19:00 | 1
16/10/2022 | 23/10/2022 | porto velho | manaus | No dia 16/10 chegar em Manaus a partir das 9:00. No dia 23/10 saída a partir das 19:00 | 4
16/10/2022 | 24/10/2022 | florianopolis | manaus | No dia 16/10 chegar em Manaus a partir das 9:00 | 1
17/10/2022 | 23/10/2022 | guarulhos | manaus | No dia 23/10 saída a partir das 19:00 | 2
17/10/2022 | 23/10/2022 | recife | manaus | No dia 23/10 saída a partir das 19:00 | 1
17/10/2022 | 23/10/2022 | salvador | manaus | No dia 23/10 saída a partir das 19:00 | 1
19/10/2022 | 23/10/2022 | recife | manaus | No dia 23/10 saída a partir das 19:00 | 1
19/10/2022 | 24/10/2022 | brasilia | manaus | não | 1
15/10/2022 | 24/10/2022 | joao pessoa | manaus | não desembarcar tarde da noite | 1
16/10/2022 | 22/10/2022 | guarulhos | manaus | volta 22 pela manha | 1
16/10/2022 | 23/10/2022 | porto velho | manaus | chegar em Manaus durante o dia (sem estar escuro) | 1
16/10/2022 | 24/10/2022 | natal | manaus | Volta - até 18h do dia 24 | 1
17/10/2022 | 21/10/2022 | vitoria | manaus | No dia 21/10 sair de Manaus até as 19:00 | 1
17/10/2022 | 23/10/2022 | salvador | manaus | viagens Preferencialmente entre 8 e 19 horas | 1
19/10/2022 | 22/10/2022 | guarulhos | manaus | verificar em tabela original (dados sensiveis)| 1
19/10/2022 | 23/10/2022 | natal | manaus | No dia 19/10 sair de Natal a partir das 17h | 1
19/10/2022 | 23/10/2022 | recife | manaus | não viajar de madrugada | 1
19/10/2022 | 23/10/2022 | recife | manaus | não viajar de madrugada | 1
20/10/2022 | 23/10/2022 | guarulhos | manaus | IDA: (1) 20/10 (quinta) à noite (19:00) OU (2) 21/10 (sex) bem cedinho (05:00) e VOLTA: 23/10 (domingo) à noite (entre 18:00 e 19:00 | 1
20/10/2022 | 24/10/2022 | guarulhos | manaus | No dia 20/10 sair de Guarulhos nas primeiras horas do dia | 1

**Comment by lipemorais** [comment]
Encontrei esse site com os vôos diretos de GRU para MAO.
http://www.emsampa.com.br/voos/guarulhos_manaus.htm
![image](https://user-images.githubusercontent.com/5021565/188334698-91df0e42-8117-4e37-8938-1beb44784c72.png)

**Comment by cecivieira** [comment]
Enviar solicitação de contação para:

Azul - grupos@voeazul.com.br

Gol - cotacao.grupos@voegol.com.br

Latam travel - 03007772000(seg-sex 9h-19h)

**Comment by cecivieira** [comment]
E-mails enviados para Gol e Azul

**Comment by cecivieira** [comment]
Todas as companhias aéreas contactadas informaram que só é tratado como grupo compras com mais de 9 pessoas por identificados. Sendo assim, as passagens serão compradas online, direto no site das companhias.

**Comment by alynnefs** [comment]
Aguardando resposta da segunda rodada de pessoas beneficiadas pelo programa

**Comment by cecivieira** [comment]
Cotação a ser solicitada para:
https://instagram.com/apeturviagens, em 16/09

**Comment by cecivieira** [comment]
Cotação solicitada:

```
Bom dia, Ana!

Segue em anexo os dados para cotação de 29 passagens aéreas. Na tabela existe data de ida, volta , cidade de origem, destino, restrições e total de passagens. ​

​Se for possível, nos envia o valor das passagens com reembolso e sem reembolso.

As passagens não terão despacho de bagagem.
```

**Comment by cecivieira** [comment]
![image](https://user-images.githubusercontent.com/30605862/190234035-2d77ad9e-e6db-4163-8f11-3f4547aebbf7.png)
![image](https://user-images.githubusercontent.com/30605862/190234120-1138b7a1-3f61-4a57-af07-b2dcb8b5db9a.png)

**Comment by cecivieira** [comment]
enviada planilha com dados consolidados e individualizados (anonimizados) solicitando atualizacao do orçamento para revisão e aprovação

**Comment by cecivieira** [comment]
Troca de forncedora de passagens aéreas para [alecrimviagens@gmail.com](mailto:alecrimviagens@gmail.com) / +55 81 9961-9027 / https://www.instagram.com/alecrimturismoeconsultoria, pois a fornecedora anterior não poderia emitir nota fiscal no valor total da compra.

**Comment by cecivieira** [comment]
Reservas emitidas.
Aguardando NFe para pagamento

**Comment by cecivieira** [comment]
Efetuada solicitação de pagamento

**Comment by lipemorais** [comment]
A nota fiscal já chegou? Quando chegando os dados para a gente fazer a comunicação com os participantes?

**Comment by cecivieira** [comment]
@lipemorais o pagamento total foi realizado agora pouco, então a fornecedora está emitindo as passagens e colocando [nessa pasta](https://drive.google.com/drive/u/1/folders/1IfxPM5rtvPeQnSh-HaUHFoZ-1Akc2y4p) . 

Com essas passagens emitidas, [a aba "voos_beneficiadas" dessa planilha] deve ser preenchida. Isso conlui essa issue.

A conclusão dessa issue desbloqueia a #41 e #23

Informações a serem coletadas: 
![image](https://user-images.githubusercontent.com/30605862/192023000-1b2c637b-2223-4e8b-a4fe-9e0cab8a0c7c.png)

**Comment by cecivieira** [comment]
Estamos com problemas em pagar as passagens por limitação na conta bancária da APyB e prazo muito curto para pagamento, por parte da agência de viagem.

Por isso as reservas ainda não estão na pasta.

**Comment by lipemorais** [comment]
A conclusão dessa issue também desbloqueia essa aqui [Comprar transporte terrestre para 2 participantes](https://github.com/pythonbrasil/pybr2022-bolsa-viagem/issues/39)

**Comment by lipemorais** [comment]
@cecivieira não subiram as novas passagens. Por onde posso falar com a pessoa que esta fazendo esse processo?  Esse Whatsapp aqui `+55 81 9961-9027`?

**Comment by cecivieira** [comment]
@lipemorais Estamos com problemas em pagar as passagens por limitação na conta bancária da APyB e prazo muito curto para pagamento, por parte da agência de viagem.

Por isso as reservas ainda não estão na pasta.

**Comment by lipemorais** [comment]
@cecivieira gostaria de assumir esse aqui para te desentulhar de coisas a fazer. Por favor, me avise se não for uma boa ideia.

Como esta em contato com o pessoal da organização? Discord? Se sim, como posso assumir esse contato?

O contato com a agência de viagens esta acontecendo por onde? Não encontrei no freshdesk.

**Comment by cecivieira** [comment]
@ lipemorais prefiro que tu assuma o #23 , pois esse processo de compra está no final , faltando a transferência de R$48mil e recepcionar as reservas emitidas. Acredito que até segunda-feira finalizamos essa issue, então prefiro seguir tocando ela.

Sim, o contato com a APyB está sendo feito via Discord e marcação aqui nas issues (@ pythonbrasil/apyb). Sim, o contato com a agência está sendo realizado via whatsapp, através do número que você menciou no comentário anterior.

**Atualização:**
Hoje realizamos o pagamento de mais R$14.964,34, então algumas novas reservas devem aparecer na pasta até o final do dia. Temos a expectativa de que até segunda-feira o resto do pagamento seja realizado e essa issue seja concluída.

Caso haja aumento na passagem aérea antes de completarmos o pagamento, será gerada uma nova nota fiscal com o valor excedente e encaminhada para pagamento via https://www.ultradox.com/app/apyb-solicitacao-pagamento .

**Comment by cecivieira** [comment]
@lipemorais prefiro que tu assuma o #23 , pois esse processo de compra está no final , faltando a transferência de R$48mil e recepcionar as reservas emitidas. Acredito que até segunda-feira finalizamos essa issue, então prefiro seguir tocando ela.

Sim, o contato com a APyB está sendo feito via Discord e marcação aqui nas issues (@ pythonbrasil/apyb). Sim, o contato com a agência está sendo realizado via whatsapp, através do número que você menciou no comentário anterior.

**Atualização:**
Hoje realizamos o pagamento de mais R$14.964,34, então algumas novas reservas devem aparecer na pasta até o final do dia. Temos a expectativa de que até segunda-feira o resto do pagamento seja realizado e essa issue seja concluída.

Caso haja aumento na passagem aérea antes de completarmos o pagamento, será gerada uma nova nota fiscal com o valor excedente e encaminhada para pagamento via https://www.ultradox.com/app/apyb-solicitacao-pagamento .

**Comment by lipemorais** [comment]
Beleza @cecivieira

**Comment by cecivieira** [comment]
Passagem compradas, pagas e reservas salvas [nesta pasta](https://drive.google.com/drive/u/0/folders/1IfxPM5rtvPeQnSh-HaUHFoZ-1Akc2y4p)
