### ISSUE TITLE
Aquisição de cartão pré-pago

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#18]
Aquisição de cartões pré-pago para pessoas beneficiadas pelo auxílio "alimentação" do Programa.
Empresa contratada: Vale Presente

Descrição do serviço:

“Cartão carga única físico não nominais que são cartões de “ gaveta’’ ( que você solicita os cartões sem vínculo  de dados, podendo ser entregue para qualquer pessoa, nessa situação os dados pessoais vinculam no momento do desbloqueio para uso).  Neste modelo não permite personalização da estampa, então você pode escolher uma de 3 modelos que temos disponíveis na plataforma, e pode ser utilizado em compras em lojas físicas e virtuais, e eles são de tarja magnética. Mínimo de carga para aquisição 50,00 reais.
Taxa para aquisição R$10,99 por unidade
 
Todos são da bandeira MasterCard, podem realizar
compras nacionais e internacionais, utilizados na função crédito à vista, mas como são pré pagos só é descontado o valor que estiver disponível no cartão, os portadores podem realizar o desbloqueio do cartão por um link ou pelo app Cartões Social Bank, as informações de desbloqueio vão na carta berço junto com os cartões.
 
Os cartões tem cobrança de taxa administrativa que pode ser paga descontada do saldo do cartão do presenteado o valor de R$1,99 a cada 30 dias se houver saldo [ou seja, caso a pessoa presentada consuma todo o saldo em 30 dias, não há cobrança de taxa administrativa para nenhuma das partes].” 

Ticket do Freshdesk: https://pythonbrasil.freshdesk.com/a/tickets/8818

**Comment by cecivieira** [comment]
@muriloviana @rougeth @anadulce @tiidadavena 

O auxílio do tipo "alimentação" será dado a pessoa beneficiada em forma de cartão presente, considerando a diária de R$31,91 (conforme prevista [nas regras do programa](https://2022.pythonbrasil.org.br/programa-auxilio-financeiro)).

Para aquisição desse produto, é necessário realizar cadastro no Social Bank através do link: https://corporate.socialbank.com.br/cadastro/inicio/ngocorp
 
Documentos solicitados para cadastro
•    Contrato/Estatuto Social da empresa;
•    Dados e cópia do RG/CNH do representante legal;
•    Procuração caso o representante mencionado não conste no contrato social;
•    Dados da pessoa que ficará responsável pelo acesso.

A APyB poderia realizar esse cadastro? 

A aquisição dos produtos deve ser feita no dia 23/09. Nós da organização do Programa informaremos quantidade e carga de cada cartão pré-pago a ser adquirido, até dia 20/09.

O cadastro deverá ser realizado com antecedência para que haja a validação do perfil da APyB em tempo hábil para aquisição do produto no dia 23/09.

**Comment by cecivieira** [comment]
Empresa escolhida na issue #13

**Comment by alynnefs** [comment]
@pythonbrasil/apyb precisam de ajuda no cadastro?

**Comment by anadulce** [comment]
Cadastro realizado. Estamos esperando um e-mail de confirmação da parte deles.

**Comment by cecivieira** [comment]
Pedido realizado e encaminhado para pagamento

**Comment by cecivieira** [comment]
Resumo do pedido:

1 u. - R$ 191,40
1u. - 319,00
9 u. - 382,80
10 u. - 478,50
