### ISSUE TITLE
Reservar hospedagem

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#19]
Reservar quartos completos com 18 camas e 4 camas, no período de 16 a 23 de outubro no valor de R$ 8.500,00 a vista (via PIX, DINHEIRO e DEBITO) na [Vila Manaus Hostel](https://pythonbrasil.freshdesk.com/a/tickets/8862)

Fonte: Issue #14

**Comment by cecivieira** [comment]
@muriloviana tu poderia pegar esse ticket para pagamento, por favor?
https://pythonbrasil.freshdesk.com/a/tickets/8862

**Comment by cecivieira** [comment]
@muriloviana é só eu pegar a nota fiscal e preencher o formulário da APyB com os dados da conta bancária para vocês fazerem o pix?

**Comment by cecivieira** [comment]
https://pythonbrasil.freshdesk.com/a/tickets/8862

**Comment by muriloviana** [comment]
olá @cecivieira, isso mesmo. Basta preencher o formulário de [solicitação de pagamento](https://www.ultradox.com/app/apyb-solicitacao-pagamento) que a requisição chega para a diretoria da APyB.

**Comment by cecivieira** [comment]
Nota fiscal solicitada com 50% do valor total da reserva.

**Comment by cecivieira** [comment]
Envio de notafiscal da 1. parcela (R$4250) para pagamento pela APyB

**Comment by cecivieira** [comment]
@pythonbrasil/apyb solicitei o pagamento via ultradocs. Vocês poderiam me enviar o comprovante de depósito por e-mail?
