### ISSUE TITLE
Ingresso - Enviar cupom de desconto para beneficiada 

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#21]
Requisito: #20

Enviar mensagem com cupom de desconto para pessoas beneficiadas com ingresso, informando sobre necessidade de inscrição usando o cupom de desconto.

**Comment by cecivieira** [comment]
@lipemorais os códigos estão disponíveis na aba "Respostas ao formulário 1", coluna AR

https://docs.google.com/spreadsheets/d/1YEXe7Mj4dIfkERmpDVIjF12LWbhH9FC-2a3h-IrGBh4/edit#gid=312878613

**Comment by cecivieira** [comment]
@pythonbrasil/pybr2022-org tem alguma data limite ideal para que as pessoas façam as inscrições no evento?

Pensei nisso porque serão produzidos os itens dos kits, então se tiver alguma data ideal, avisa pra explicitarmos no e-mail com o código.

**Comment by julianyraiol** [comment]
Oi gente, precisamos que seja feito até o fim do mês, dia 30.09 por conta das camisas
