### ISSUE TITLE
Alimentação - Informar sobre recebimento de benefício 

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#22]
Requisito: #18

Informar beneficiadas com auxílio "alimentação", local , data e horário para pegar o cartão pré -pago.

No mesmo email informar que é um cartão pré pago com saldo XXXXX (verificar na planilha, pois o saldo é correspondente aos dias no evento) com a bandeira Mastercard, que pode ser usado em qualquer estabelecimento e que as instruções para desbloqueio será entregue junto com o cartão.

**Comment by cecivieira** [comment]
Trecho de email:

Os créditos desse cartão devem ser consumidos até o dia 24/10. Após está data será descontado do saldo a taxa de R$1,99 por mês, caso ainda haja saldo remanescente. O saldo completo expirará na data de 16/12/2022.

Não está habilitada a função de saque este cartão

**Comment by cecivieira** [comment]
Rascunho: https://docs.google.com/document/d/1WMfN38qv_6LovOSyE-gzV9c3a6kfiMNvPPCtIdWAe6w/edit

**Comment by cecivieira** [comment]
@lipemorais @alynnefs vocês poderiam dá uma revisada nesses texto?

Se você fosse uma das pessoas a receber. Gostaria de saber mais alguma informação sobre o uso do cartão?

https://docs.google.com/document/d/1WMfN38qv_6LovOSyE-gzV9c3a6kfiMNvPPCtIdWAe6w/edit

**Comment by felipythondev** [comment]
Gostei do texto, adicionei um assunto para o e-mail.

**Comment by cecivieira** [comment]
e-mail enviado
