### ISSUE TITLE
Transporte - Enviar email com passagem aérea 

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#23]
Requisito : #15

Enviar passagem aérea para cada beneficiada.

Pasta com passagens aéreas: 
https://drive.google.com/drive/u/1/folders/1IfxPM5rtvPeQnSh-HaUHFoZ-1Akc2y4p

**Comment by cecivieira** [comment]
@pythonbrasil/apyb é possível solicitar apoio jurídico para revisar os termos abaixo? Seu objetivo é informar as beneficiadas pelo Programa que qualquer ônus ocorrido por sua falha/quebra dos termos descrito na passagem aérea é de sua responsabilidade.

"
Qualquer intercorrência oriunda da companhia aérea deve ser tratada diretamente com a companhia. Caso seja necessária intermediação da agência emissora da passagem aérea, favor contactar Apetur viagens através do telefone +55 71 8163-3775 e registrar através de email apeturismo@gmail.com. 

É de responsabilidade da pessoa beneficada qualquer ônus referente a quebra dos termos de serviço da companhia aérea (ex.: noshow, remarcação de passagens, etc).
"

Caos não seja possível essa consulta ao jurídico, avisa, por favor.

**Comment by cecivieira** [comment]
Trecho:

Olá,

Estamos muito felizes que vamos te encontra na Python Brasil!!!

Em anexo está a sua passagem aérea. Tentamos aí máximo adequar o horário a sua preferência de viagem, mas pode ser que não tenhamos conseguido.

Te informamos que (trecho comentário anterior).

Nos vemos em breve!!

**Comment by cecivieira** [comment]
Aguardando emissão das reservas

**Comment by rougeth** [comment]
Eu só vi a mensagem sobre a consulta jurídica agora, ainda é válido/necessário?

**Comment by cecivieira** [comment]
Ainda dá tempo @rougeth.
Vamos informar sobre as passagens na segunda-feira.

**Comment by rougeth** [comment]
Se o prazo foi segunda, acho difícil de conseguirmos um feedback.

**Comment by cecivieira** [comment]
@rougeth tu acha que a gente consegue até sexta-feira (30)?

**Comment by cecivieira** [comment]
Pasta com passagens aéreas: 
https://drive.google.com/drive/u/1/folders/1IfxPM5rtvPeQnSh-HaUHFoZ-1Akc2y4p

**Comment by muriloviana** [comment]
@cecivieira me tira uma dúvida, essa parte que tu mencionou:

> 
> Qualquer intercorrência oriunda da companhia aérea deve ser tratada diretamente com a companhia. Caso seja necessária intermediação da agência emissora da passagem aérea, favor contactar Alecrim Turismo e Consultoria através do telefone +55 81 9961-9027 e registrar através de email [alecrimviagens@gmail.com](mailto:alecrimviagens@gmail.com).
> 
> É de responsabilidade da pessoa beneficada qualquer ônus referente a quebra dos termos de serviço da companhia aérea (ex.: noshow, remarcação de passagens, etc).

Será acrescido ao Programa de Auxílio Financeiro para a Python Brasil 2022 (no caso, O README.md desse repo) ou isso faz parte de outro documento? Se for outro, consegue me passar por gentileza.

**Comment by cecivieira** [comment]
@muriloviana esse trecho faria parte do e-mail de entrega da passagem aérea. 

Na real esse trecho expressa uma ideia de mensagem que precisamos passar para as pessoas beneficiadas pelo programa. No fim das contas, o que precisamos nos assegurar é que a pessoa entenda que nós emitimos a passagem e qualquer outro ônus é dela. Além disso, o suporte com o transporte aéreo será dado pela agência de viagem.

Esse é o texto completo que está sendo pensado:
https://github.com/pythonbrasil/pybr2022-bolsa-viagem/blob/main/modelo_email_envio_auxilio_transporte.md

**Comment by lipemorais** [comment]
Desbloqueado pois as passagens aéreas já foram compradas: https://github.com/pythonbrasil/pybr2022-bolsa-viagem/issues/15

@cecivieira só mudaria `noshow` por `não comparecimento`.

@cecivieira posso enviar os e-mails na segunda mesmo? Ou precisamos esperar o ok do jurídico?

- [ ] Confirmar a data do envio
- [ ] Separar algumas pessoas para me ajuda no envio
- [ ] Enviar e-mails cada uma das pessoas beneficiadas

**Comment by lipemorais** [comment]
Passagens compradas.
Reservas guardadas na [pasta de reservas
](https://drive.google.com/drive/u/0/folders/1IfxPM5rtvPeQnSh-HaUHFoZ-1Akc2y4p) para serem enviadas junto com a passagem aérea.
Fonte: https://github.com/pythonbrasil/pybr2022-bolsa-viagem/issues/39#issuecomment-1257008645

**Comment by cecivieira** [comment]
@lipemorais  Todas as passagens já estão disponíveis na pasta. É importante observar que existem passageiras com 2 arquivos, isso ocorre porque a ida e a volta foram emitidas em cia aéreas diferentes ou tem transporte rodoviário também. Sendo assim, ambos os arquivos devem ser enviados para a beneficada.

[Aqui tem uma sugestão de texto para e-mail,](https://github.com/pythonbrasil/pybr2022-bolsa-viagem/blob/main/modelo_email_envio_auxilio_transporte.md) mas seria interessante aguardar resposta da APyB (ler thread para entender o contexto) antes de enviar as passagens. Acredito que um prazo interessante para esperar resposta é até dia 30 set.

Por favor, caso o e-mail seja diferente [dessa sugestão](https://github.com/pythonbrasil/pybr2022-bolsa-viagem/blob/main/modelo_email_envio_auxilio_transporte.md), sobe um commit com a modificação.

**Comment by muriloviana** [comment]
Olá @cecivieira e @lipemorais, já acionamos o jurídico para revisar o email. Acredito que até amanhã temos um ok ou alterações.

**Comment by lipemorais** [comment]
Obrigado @muriloviana ! Ficamos no aguardo.

**Comment by muriloviana** [comment]
Pessoal, termo sugerido pelo jurídico: https://docs.google.com/document/d/1OxhxIphwPUKwgiKUfmI1iONzNn-9MX9k/edit?usp=sharing&ouid=102328710314716225444&rtpof=true&sd=true

Comentários e sugestões são sempre bem-vindos

**Comment by lipemorais** [comment]
@muriloviana a ideia seria mandar esse termo no e-mail junto com o ingresso?

**Comment by cecivieira** [comment]
@lipemorais a ideia é sim enviar esse termo de repsonsabilidade junto

**Comment by alynnefs** [comment]
vcs acham que é necessário enviar para assinatura usando o docsign? ou só png da assinatura resolve?

**Comment by cecivieira** [comment]
@alynnefs acho que a conta gratuita do Docsign não nos atende, pois limita a quantidade de assinaturas por mês.
Acredito que se a beneficiada responder no e-mail "Li e concordo/aceito o Termo de responsabilidade" já pode ser suficiente. Deixa eu conferir com o advogado

**Comment by cecivieira** [comment]
@lipemorais Esse termo deve ir no corpo do e-mail, abaixo de tudo (não coloca como anexo). Deve ser solicitada as beneficiadas que respondam ao e-mail informando que "leu e que aceita as condições do termo".

De acordo com o consultor jurídico (Bruno Morassutti) da APyB, a resposta ao e-mail já é suficiente.

**Comment by lipemorais** [comment]
Beleza, vou me prepara para começar a enviar hoje ao fim do dia então.

**Comment by muriloviana** [comment]
Vi que o @lipemorais havia levantado uma dúvida mas já foi esclarecido. Temos mais alguma observação, comentário ou sugestão quanto ao termo? Ou posso considerar ele como aprovado?

**Comment by cecivieira** [comment]
Pode considerar como aprovado.

**Comment by cecivieira** [comment]
E-mail enviado pelo MailChimp e criada coluna na [tabela de beneficiadas](https://docs.google.com/spreadsheets/d/1YEXe7Mj4dIfkERmpDVIjF12LWbhH9FC-2a3h-IrGBh4/edit#gid=312878613) para verificar aceitação do termo.
