### ISSUE TITLE
Solicitar instruções de boa convivência para hostel

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#25]
Solicitar ao hostel https://instagram.com/vilahostelmanaus guia de boa convivência no local, ex:

- silencio entre x e y horas
- não leve comida pro quarto

Etc.

**Comment by alynnefs** [comment]
instruções comentadas em: https://github.com/pythonbrasil/pybr2022-bolsa-viagem/issues/24#issuecomment-1254138011

**Comment by desi-me** [comment]
Regras enviadas pelo hostel:

VILA HOSTEL REGRAS 2022: https://docs.google.com/document/d/1XnC0uaKiRpIyYna6G8WW2dXej3qGjQra/edit

REGRAS VILA HOSTEL MANAUS 2022: https://docs.google.com/document/d/13ECoUoDiT2jvS9uSvyxTBqv4dNXh8Mqv/edit
