### ISSUE TITLE
Apoio Fundação Da Hora

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#27]
Registrar o processo de potencial apoio da Fundação Da Hora.

Ticket freshdesk: https://pythonbrasil.freshdesk.com/a/tickets/8662

**Comment by cecivieira** [comment]
e-mail recebido:

```
Oi Ana simm consegui, podemos marcar na sexta ? 
Vamos conseguir apoiar viagem e tava pensando em algo relacionado a cursos e ou livros também, o que tu acha? 
```

**Comment by cecivieira** [comment]
Enviada confirmação de reunião na sexta.
Aguardando repsosta de melhor horário para a Fundação.

**Comment by lipemorais** [comment]
@cecivieira essa reunião aconteceu? Teve alguma atualização? Quer passar essa issue para outra pessoa atuar?

**Comment by cecivieira** [comment]
@lipemorais a reunião não aconteceu. Acredito que Nina está com a agenda muito aperta, pois está sendo um pouco difícil consegui respostas.

Prefiro passar essa issue para outra pessoa atuar.

**Comment by lipemorais** [comment]
@marinedran poderia/gostaria de assumir esse aqui?

**Comment by cecivieira** [comment]
Tendo em vista que restam apenas 22 dias para o evento. Acredito que não temos tempo hábil para passar por todo o processo de patrocínio e executar o dinheiro.
