### ISSUE TITLE
Criar fluxo de caixa

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#28]
Criar fluxo de caixa conforme orientação da @pythonbrasil/apyb .

**Comment by cecivieira** [comment]
@pythonbrasil/apyb vamos fazer o primeiro gasto. Como devemos fazer o registro do caixa (receita e despesa) ? Existe uma planilha modelo? Algum sistema?

**Comment by muriloviana** [comment]
@cecivieira não existe um modelo de caixa ou planilha.

Basicamente, o grupo de pessoas organizadoras da bolsa de viagem tem total liberdade para escolher a melhor forma de gerenciar o caixa. A APyB apenas verifica as movimentações na conta bancária da associação identificando as entradas e saídas referentes, através das solicitações dos formulários do Ultradox.

**Comment by cecivieira** [comment]
Obrigada @muriloviana 


Fluxo de Caixa disponível em: https://docs.google.com/spreadsheets/d/1YEXe7Mj4dIfkERmpDVIjF12LWbhH9FC-2a3h-IrGBh4/edit#gid=442361531

**Comment by rougeth** [comment]
@cecivieira já temos issue para o relatório final?

**Comment by cecivieira** [comment]
@rougeth tem a issue #30
