### ISSUE TITLE
Patrocínio da Lend

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#29]
Registrar o processo de potencial patrocínio da empresa Lend.

**Comment by cecivieira** [comment]
a Lend está em processo de patrocínio com a Python Brasil e na última reunião mostraram interesse em financiar ingressos.

A organização da PyBR nos convidou para uma reunião hoje as 20h30 para tentar montar uma proposta em conjunto.

Para aocmpanhar a negociação, olha esse ticket: https://pythonbrasil.freshdesk.com/a/tickets/8694

**Comment by cecivieira** [comment]
Tendo em vista que a empresa comprará a cota bronze, com isso já terá exposição da marca no site e menção no palco, foi sugerida que as contrapartidas adicionais sejam:

- presença na postagem coletiva sobre empresas apoiadoras do programa (padrão do plano de apoio)
- exibição de marca no rodapé do e-mail de relatório enviado a todas as participantes e empresas do evento (adicional. vale explicitar que no rodapé constarãoi todas as empresas apioadoras do programa)

**Comment by lipemorais** [comment]
Ta fechado isso aqui, @cecivieira? Pode mover para done ou tem coisas para fazer ainda?

**Comment by cecivieira** [comment]
@wasp-lahis @julianyraiol como tá a negociação com a Lend? Deram resposta?

cc @lipemorais

**Comment by wasp-lahis** [comment]
Oie gente, enviei a proposta que definimos na reunião geral e o ultimo email deles foi em 19/10:

> Obrigado Lahis pelo retorno. Vou analisar aqui com --- e te retorno breve.
> Muito obrigado também por esse feedback dos cordões, foi algo que não chegou antes para a gente, tomaremos mais cuidado da próxima vez.
> 
> Até breve,

Vou cobrar um posicionamento novamente.

**Comment by cecivieira** [comment]
Empresa não tem mais interesse em patrocinar o evento.
