### ISSUE TITLE
Desenvolver critérios para escolha de pessoas beneficiárias

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#3]
### Descrição
Desenvolver critérios para escolha de pessoas beneficiárias considerando os seguintes pontos:

- Dias de evento que pode participar
- Raça e Etnia
- Gênero
- Sócio econômico
- Palestrantes

### Requisitos para a atividade ser considerada como concluída
- Critérios definidos e registrados

**Comment by alynnefs** [comment]
Sugestões:

- se está trabalhando ou não (deve entrar no sócio econômico)
- se está em processo de migração de carreira
