### ISSUE TITLE
Escrever critérios de seleção de beneficiadas

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#30]
Escrever e publicar critérios usados na escolha das pessoas beneficiadas pelo programa

**Comment by lipemorais** [comment]
Isso aqui seria tipo uma prestação de contas dos critérios utilizados na seleção, certo?

**Comment by cecivieira** [comment]
@lipemorais a ideia é redatar um texto sobre os critérios utilizados para seleção das pessoas beneficiadas e subir aqui no repositório, afim de documentar e explicitar quais grupos foram beneficados e o nível de prioridade dado a cada um.

Esse texto também fará parte do relatório de prestação de contas #31.

**Comment by cecivieira** [comment]
6. Pessoas brancas residentes no estado do Amazonas

**Comment by cecivieira** [comment]
Rascunho:

https://docs.google.com/document/d/1v5wCxAPUXSMTrXcRAuZlUFIwF7ejz9evFslt9KqKboY/edit

**Comment by cecivieira** [comment]
@lipemorais @alynnefs @maribedran vocês poderiam dá uma revisada nesses texto?
A ideia é deixar explícito como nós selecionamos as pessoas beneficiadas.

https://docs.google.com/document/d/1v5wCxAPUXSMTrXcRAuZlUFIwF7ejz9evFslt9KqKboY/edit
