### ISSUE TITLE
Patrocínio Lincoln Loop

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#33]
Registrar o processo de potencial patrocínio da empresa Lincoln Loop.

**Comment by cecivieira** [comment]
Enviada minuta do contrato

**Comment by cecivieira** [comment]
contrato assinado e invoice enviados

pasta do patrocinio https://drive.google.com/drive/u/1/folders/1Fnv5YxG2PWC3osN1JbqXpmc8KeFzFtwx

aguardando pagamento

**Comment by cecivieira** [comment]
@muriloviana tu poderia pegar esse ticket: https://pythonbrasil.freshdesk.com/a/tickets/8970 ?

É o processo de recebimento do patrocínio da Lincoln

**Comment by muriloviana** [comment]
Posso sim, vlws 👍

**Comment by cecivieira** [comment]
@maribedran já respondemos o formulário que recebemos da empresa. Tu poderia dá uma olhadinha sobre os trâmites? Não recebemos nenhuma outra mensagem depois do preenchimento (26/09/2022)

**Comment by maribedran** [comment]
Pedi aqui pra verificarem o status do pagamento.

**Comment by cecivieira** [comment]
@muriloviana tu poderia verificar se recebemos esse dinehiro e qual foi o valor?

**Comment by muriloviana** [comment]
@cecivieira, não recebemos ainda. Inclusive tá bem amarrado o recebimento na plataforma sugerida por eles https://www.veem.com. No dia 29/09 a transação ficou parada devido a falta de dados pessoais de um responsável pela APyB. Subi os dados semana passada e desde então tá travado lá.

Tu teria o contato de alguém da Lincoln Loop para verificarmos o porquê de não ter sido feito o pagamento ainda?

**Comment by cecivieira** [comment]
@muriloviana a @maribedran está fazendo essa ponte com a empresa.

**Comment by maribedran** [comment]
@muriloviana perguntei aqui e já te dou um retorno

**Comment by cecivieira** [comment]
@maribedran tu poderia enviar logo da empresa para colocarmos no site?

**Comment by maribedran** [comment]
https://lincolnloop.com/brand/ 4c Full Logo (Preferred)

**Comment by maribedran** [comment]
@muriloviana parece que agora sim foi o pagamento, né? Recebi uma notificação aqui. @cecivieira depois me confirma se precisa de mais alguma coisa.

**Comment by muriloviana** [comment]
Olá @maribedran, recebemos o pagamento sim. Vlw pela ajuda \o/

**Comment by cecivieira** [comment]
@muriloviana tu poderia informar o valor exato do patrocínio? 
Por favor, comenta e fecha essa issue.

**Comment by muriloviana** [comment]
Valor do patrocínio: R$ 5.069,78
