### ISSUE TITLE
Convocar para foto oficial 

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#34]
Enviar e-mail para todas as pessoas beneficiadas, convocando para foto ofical do Programa de Auxílio Financeiro para o dia 20 de outubro as 16h no banner da entrada principal.

**Comment by cecivieira** [comment]
Rascunho: 
https://docs.google.com/document/d/16tLoaLC0gEjXCtDOdCEKP_p7OblrfYeuXP05CCOhctw/edit

**Comment by cecivieira** [comment]
@lipemorais @alynnefs vocês poderiam dá uma revisada nesses texto? A ideia é que ele seja enviado no dia 12 out.

Pensei em tirarmos uma foto oficial com todas as beneficadas pelo programa para fazer divulgação e colocar no relatório.

https://docs.google.com/document/d/16tLoaLC0gEjXCtDOdCEKP_p7OblrfYeuXP05CCOhctw/edit

**Comment by felipythondev** [comment]
Posso sim, vou fazer isso agora pela manhã.

**Comment by felipythondev** [comment]
Achei o texto bom só fiquei com uma dúvida em relação ao dia e horário.

**Comment by cecivieira** [comment]
@lipemorais dia 20 é o primeiro dia do evento. Todas as beneficiadas estarão na cidade, exceto 1.
Acredito que fazer a foto no primeiro dia do evento também vai proporcionar integração entre elas, além de nos conhecer (consequentemente,s aber a quem recorrer, caso precisem).

**Comment by felipythondev** [comment]
Bons pontos m

**Comment by cecivieira** [comment]
Envio de e-mail agendado para 12 out. as 8h30 (gmt-3)
