### ISSUE TITLE
Comprar transporte terrestre para 2 participantes

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#39]
- Comprar transporte intermunicipal para que 2 participantes se desloque até o aeroporto da capital mais próxima.
- Enviar para participantes

**Observações:**
participantes índice: 20 e 86

empresa de transporte rodoviário: https://progressoonline.com.br/

Verificar horário do voo das participantes para que cheguem na cidade com 3h de antecedência do voo.

**Comment by cecivieira** [comment]
Dados dos voos:
https://docs.google.com/spreadsheets/d/1YEXe7Mj4dIfkERmpDVIjF12LWbhH9FC-2a3h-IrGBh4/edit#gid=312878613

**Comment by lipemorais** [comment]
Como a gente faz para pagar isso aqui? 

As opções no site da empresa são:
1. Boleto
2. Cartão de crédito
3. Pix


Depois disso ficaria faltando:

- [ ] Mandar o e-mail para as pessoas beneficiadas

Cc.: @maribedran

**Comment by cecivieira** [comment]
Nesse caso de não haver pagamento por boleto, um de nós pode pagar e solicitar reembolso da APyB através do formulário https://www.ultradox.com/app/apyb-solicitacao-reembolso .

Recomendo a compra das passagens rodoviárias depois da emissão da passagem aérea, assim conseguimos coordenar melhor o tempo dessa conexão.

A origem da passagem rodoviária é Sertânia-PE.

@lipemorais @maribedran

**Comment by lipemorais** [comment]
@cecivieira as duas passagens são de Sertânia-PE? A informação vem desse [ticket](https://pythonbrasil.freshdesk.com/a/tickets/8721) aqui certo?

**Comment by cecivieira** [comment]
@lipemorais sim, o ticket está correto. Ambas as passagens é saindo de Sertânia para Recife, pois é o aeroporto mais próximo.
A resposta não está no e-mail, pois entrei em contato por telefone com as beneficiadas.

**Comment by cecivieira** [comment]
Contato realizado com as beneficiadas solicitando RG, pois no site só tem essa opção de documento. Aguardando resposta para adquirir as passagens rodoviária.

**Comment by cecivieira** [comment]
Passagens compradas.
Reservas guardadas na [pasta de reservas](https://drive.google.com/drive/u/0/folders/1IfxPM5rtvPeQnSh-HaUHFoZ-1Akc2y4p) para serem enviadas junto com a passagem aérea.
