### ISSUE TITLE
Definir programa de auxílio financeiro

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#4]
### Descrição
Descrever programa, público alvo e regras

**Comment by cecivieira** [comment]
Rascunho:
https://docs.google.com/document/d/1pDs4A7aRYZYoHNx4TCdGrYu3JSGvLgbYY9Elr3PUQ2U/edit?usp=sharing

**Comment by cecivieira** [comment]
Aguardando revisão de @lipemorais

**Comment by cecivieira** [comment]
@gabubellon @cuducos

**Comment by gabubellon** [comment]
@cecivieira no caso seria ajuda para revisar o documento que será utilizado no site ?
A revisão dever ser somente de portugues ou devemos nos atentar para algum item que precise ser alinhado ?

**Comment by cecivieira** [comment]
@gabubellon essa é a descrição completa da bolsa. Pode sugerir alterações de conteúdo, pois esse documento reflete só o que tô pensando.

Ele está aberto para alinhamento de pontos e revisão até dia 19/08. Sinto muito o prazo curtíssimo, mas não tive tempo de puxar a iniciativa com antecedência.

**Comment by alynnefs** [comment]
Eu achei o texto muito bom. Considerando que os responsáveis são PyLadies Brasil, AfroPython e organização, apenas brasileiros podem pedir auxílio? Se sim, não vejo necessidade de traduzir pra outras línguas

**Comment by cecivieira** [comment]
@alynnefs sim, apenas para pessoas que estão no Brasil podem solicitar transporte. Não temos orçamento para custear passagem internacional.

É necessário escrever os critérios para escolha de pessoas a serem beneficiadas. Da Uma olhadinha nessa issue também, por favor (não tem nada).

Escrevi essa descrição para ser usada como base para desenvolver as outras ações como, formulário de submissão , critérios etc.

**Comment by cecivieira** [comment]
Prazo limite para revisão e envio de sugestão de alterações: 19 ago.
