### ISSUE TITLE
Enviar nota fiscal dos cartões para APyB

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#40]
- Solicitar nota fiscal da Vale Presente
- Receber nota fiscal
- Enviar para APyB

Ticket do freshdesk: https://pythonbrasil.freshdesk.com/a/tickets/8818

**Comment by cecivieira** [comment]
@pythonbrasil/apyb essa compra já foi paga usando o comprovante do pedido. Atualmente já solicitamos a emissão da nota fiscal.
Como devemos enviar essa nota fiscal para vocês? Tendo em vista que não é mais necessário nenhum pagamento.

**Comment by muriloviana** [comment]
@cecivieira, por gentileza, pode mandar diretamente para diretoria@python.org.br mencionando essa mesma issue.

**Comment by felipythondev** [comment]
@cecivieira alguma novidade sobre isso aqui?

**Comment by cecivieira** [comment]
@lipemorais Hoje enviei uma nova solicitação de nota fiscal

**Comment by cecivieira** [comment]
Nota fiscal enviada:
https://pythonbrasil.freshdesk.com/a/tickets/9323
