### ISSUE TITLE
Enviar tabela de chegada de hóspedes para Hostel

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#41]
Requisito: #15 

Enviar para hostel Vila Manaus ([ticket freshdesk](https://pythonbrasil.freshdesk.com/a/tickets/8862)) tabela de chegada de cada hóspede.

A tabela a ser extraída é voos_beneficiada [desta planilha](https://docs.google.com/spreadsheets/d/1YEXe7Mj4dIfkERmpDVIjF12LWbhH9FC-2a3h-IrGBh4/edit#gid=469272370) com o filtro de hospedagem aplicado. Extrair para xls e enviar por e-mail.

**Comment by lipemorais** [comment]
@cecivieira esse ticket esta bloqueado pela confirmação das passagens aéreas?

**Comment by cecivieira** [comment]
@lipemorais Isso.
Pensei em mandar uma segunda mensagem para as pessoas que receberam passagem aérea e colocando data limite para confirmação do uso da passagem.

Uma boa parte delas vai pra o hostel, então se mais alguem desistir, precisamos repactuar o contrato.

Tu poderia ajudar a construir esse texto #48 ? Pensei em na primeira frase dele colocar CONFIRME O USO DA PASSAGEM hehehehe.

**Comment by lipemorais** [comment]
Tem visibilidade de quantas pessoas ainda não confirmaram?

**Comment by cecivieira** [comment]
@lipemorais 2 pessoas desistiram:

- 1 pessoa desistiu de todo o benefício;
- 1 pessoa desistiu da hospedagem, por ser em quarto compartilhado.

A pessoa que desistiu do benefício, ele será relocado para outra pessoa. No entanto, ainda não temos os horários de chegada dessa nova beneficiada (ver #45). Sua passagem deverá ser adquirida esse final de semana.

**Comment by cecivieira** [comment]
E-mail enviado
