### ISSUE TITLE
Decidir sobre uso de dinheiro excedente

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#43]
Com a finalização da compra das passagens aéreas, temos um excedente de R$24mil. Por isso, proponho atender as seguintes pessoas:

| indice_pessoa | observacao | custo_estimado |
| --|--|--|
| 84 | respondeu depois do prazo. solicitou ingresso e alimentacao. Acredito que poderíamos atender a alimentação em formato de reembolso, respeitando o limite estabelecido | R$ 525,20 |
| 7 | desistiu do benefício porque solicitou apenas hospedagem e atualmente passagem está muito cara. Acredito que poderíamos expandir o benefício para cobrir passagem e hospedagem | R$ 3.754,74 |
| 85| palestrante que não foi informada na 1. lista enviada pela organização. Solicitou transporte aéreo | R$ 3.350 |
| --| TOTAL | R$7.629,94

**Comment by cecivieira** [comment]
@lipemorais @alynnefs @desi-me @maribedran vocês poderiam opinar sobre isso? Seria interessante termos uma decisão até dia 28 set.

**Comment by lipemorais** [comment]
Concordo acho que dá pra beneficiar essas pessoas  sim.

**Comment by maribedran** [comment]
Também acho que dá pra beneficiar sim.

**Comment by maribedran** [comment]
Temos 6 pessoas na lista que só pediram ingresso e uma delas alimentação. Acho que seria viável incluir elas já que não tem a questão do tempo de compra de passagem e reserva de hospedagem. São todas do AM, 4 mulheres e 2 homens.

**Comment by desi-me** [comment]
Por mim libera tudo. Incluindo o que a @maribedran trouxe. Se for dentro do valor estabelecido.

**Comment by cecivieira** [comment]
Massa!!!

O quadro final de pessoas a serem beneficiadas com o dinheiro excedente:

| indice_pessoa | observacao | custo_estimado |
| --|--|--|
| 84 | respondeu depois do prazo. solicitou ingresso e alimentacao. Acredito que poderíamos atender a alimentação em formato de reembolso, respeitando o limite estabelecido | R$ 525,20 |
| 7 | desistiu do benefício porque solicitou apenas hospedagem e atualmente passagem está muito cara. Acredito que poderíamos expandir o benefício para cobrir passagem e hospedagem | R$ 3.754,74 |
| 85| palestrante que não foi informada na 1. lista enviada pela organização. Solicitou transporte aéreo | R$ 3.350 |
| --|--|--|
| --|--|--|
| --|--|--|
| --|--|--|
| --|--|--|
| --|--|--|
| --|--|--|
| --|--|--|
| --|--|--|
| --| TOTAL | R$7.629,94

**Comment by cecivieira** [comment]
Massa!!!

O quadro final de pessoas a serem beneficiadas com o dinheiro excedente:

| indice_pessoa | observacao | custo_estimado |
| --|--|--|
| 84 | respondeu depois do prazo. solicitou ingresso e alimentacao. Acredito que poderíamos atender a alimentação em formato de reembolso, respeitando o limite estabelecido | R$ 525,20 |
| 7 | desistiu do benefício porque solicitou apenas hospedagem e atualmente passagem está muito cara. Acredito que poderíamos expandir o benefício para cobrir passagem e hospedagem | R$ 3.754,74 |
| 85| palestrante que não foi informada na 1. lista enviada pela organização. Solicitou transporte aéreo | R$ 3.350 |
| 50|nova beneficiada. Solicitou ingresso e alimentação|R$ 748,5|
| 54|nova beneficiada. Solicitou ingresso|R$270|
| 55|nova beneficiada. Solicitou ingresso|R$270|
| 56|nova beneficiada. Solicitou ingresso|R$270|
| 57|nova beneficiada. Solicitou ingresso|R$270|
| 58|nova beneficiada. Solicitou ingresso|R$270|
| --| TOTAL | R$9.728,44
