### ISSUE TITLE
Reunir desistências 

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#45]
Reunir desistências do Programa de Benefícios de última hora e realizar tratativas.

Inserir link do ticket do freshdesk.

**Comment by alynnefs** [comment]
desistência de passagem: https://pythonbrasil.freshdesk.com/helpdesk/tickets/9039
solicitou ingresso, alimentação, hospedagem e transporte aéreo

**Comment by cecivieira** [comment]
@alynnefs Tratativa dada a beneficiada índice 3:

- Alimentação: Redristribuição para beneficiada indice 50
- Ingresso: Redristribuição para beneficiada indice 50
- Hospedagem: Redistribuição para beneficiária indice 7
- Transporte: Tentar redistribuição para beneficiária indice 7

**Comment by cecivieira** [comment]
Beneficiado 13 desistiu do alojamento:

- Solução sugerida: Transferi para beneficiada 65, que havia desistido da hospedagem inicialmente

**Comment by cecivieira** [comment]
Beneficiado 83 desistiu do alojamento:

    Solução sugerida: Desfazer reserva entre 19 e 24 de set.

**Comment by cecivieira** [comment]
Mensagem enviada solicitando desfazimento das reservas
