### ISSUE TITLE
Café da manhã para hospedagem

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#49]
O hostel não fornece café da manhã.

O evento fornecerá coffee break de 9h as 9h30 entre 20 e 23 de outubro, então solicitei orçamento do hostel para café da manhã entre 17 e 19 de outubro. Segue a proposta enviada:

![Image](https://user-images.githubusercontent.com/30605862/193339505-2f0da89f-9a81-4ebe-8cd2-4c0341b413ce.png)

Vocês acham qeu deveríamos adquirir esse serviço complementar?
cc @alynnefs @maribedran @lipemorais

**Comment by alynnefs** [comment]
@cecivieira, é uma boa solicitar sim. Só tem que ver se vai ter de fato 23 pessoas nesses dias, mas o envio dos dias de chegada resolvem o problema. O pagamento tem que ser feito antes?

**Comment by cecivieira** [comment]
@alynnefs tô verificando se emite nota fiscal separada ou se será na mesma da segunda parcera da hospedagem.

**Comment by cecivieira** [comment]
-> Valor total Café da Manhã: R$615,00 
17/10 - 11 Pessoas R$165,00
18/10 - 15 Pessoas R$225,00
19/10 - 15 pessoas R$225,00

Nota fiscal emitida conjuntamente com a 2. parcela da hospedagem
