### ISSUE TITLE
Contratação de Espaço Kids

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#50]
Tendo em vista que Espaço Kids é uma necessidade, principalmente, para viabilizar a participação do evento por mulheres, este ano ele será promovido pelo Programa de Auxílio Financeiro.

**Tarefas**
- Levantamento orçamentário junto a fornecedoras
- Revisão de contrato
- Assinatura do contrato

**Comment by cecivieira** [comment]
Contrato para análise:
https://drive.google.com/file/d/17VynMXlV6zOJoeFCRLjpJ7I9UZa-SBsS/view?usp=sharing

**Comment by felipythondev** [comment]
Esse contrato deve ser revisado pelo jurídico da APyB? O @muriloviana nos ajuda nessa também?

**Comment by cecivieira** [comment]
@lipemorais não.
enviei sugestão de alteração do contrato e estou aguardando a nova versão.

**Comment by cecivieira** [comment]
Contrato assinado. 
Aguardando nota fiscal

**Comment by cecivieira** [comment]
Modificações realizadas no contrato:

item 3.1.2 - Incluir nas atividades prestadas o controle de entrada e saída de crianças no espaço
item 3.1.4 - O horário do espaço kids entre os dias 20 e 22 deve ser das 9h até as 18h. No dia 23 das 9h às 16h.
item 4.1 - A primeira parcela do pagamento será realizado até dia 14 de outubro e a segunda parcela no dia 24 de outubro (primeiro dia útil após a prestação do serviço)

Ticket: https://pythonbrasil.freshdesk.com/a/tickets/9176

**Comment by cecivieira** [comment]
Enviada nova solicitação de nota fiscal e dados bancários para pagamento. Aguardando repsosta da fornecedora.
