### ISSUE TITLE
Realizar postagem de agradecimento para empresas patrocinadoras

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#52]
Realizar postagem de agradecimento para empresas patrocinadoras

- PSF
- Fundo para Inclusão da APyB
- Lincool
- Alura (? verificar andamento do contrato)
- Empresas do Apydrinhamento

**Comment by cecivieira** [comment]
@tiidadavena manda a logo da APyB, por favor.

**Comment by cecivieira** [comment]
@wasp-lahis quais empresas contribuiram com apydrinhamento?

**Comment by wasp-lahis** [comment]
> @wasp-lahis quais empresas contribuiram com apydrinhamento?

R: As empresas que contribuiriam estão destacadas em azul na [1º coluna dessa planilha](https://docs.google.com/spreadsheets/d/1mKnLb_j7D645KcbX5sOBhToVg9bMcwmm/edit?usp=sharing&ouid=104240651414053856255&rtpof=true&sd=true)

**Comment by cecivieira** [comment]
@pythonbrasil/apyb aonde encontro a logo da APyB?

**Comment by cecivieira** [comment]
https://twitter.com/pythonbrasil/status/1588610191792160769

https://www.instagram.com/p/CkjOKHxrZx0/

https://www.linkedin.com/feed/update/urn:li:activity:6994375887165001728
