### ISSUE TITLE
Reembolso beneficiada indice 7

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#54]
Reembolsar R$404,74 para beneficiada indice 7.

Ticket: https://pythonbrasil.freshdesk.com/a/tickets/9024

**Comment by cecivieira** [comment]
@muriloviana uma beneficiada será reembolsada da sua estadia devido a uma intercorrencia. Ela dividiu um Airbnb com outras pessoas, ou seja, não existe nota fiscal. Que tipo de comprovante ela pode apresentar?

Pensei em um recibo com período de hospedagem, nome completo, data de emissão do recibo e valor da parte dela no airbnb. Isso faz sentido?

**Comment by muriloviana** [comment]
@cecivieira se ela conseguir o nome completo da pessoa que contratou o Airbnb, juntamente com o comprovante do Airbnb, além do nome dela e o valor que ela pagou, acredito que seja suficiente.

**Comment by cecivieira** [comment]
Reembolso solicitado a APyB.

Recibos:
https://drive.google.com/file/d/1LGbu-Txpc_xH3x4NuRrtWMaqoMeG4R7-/view?usp=share_link
https://drive.google.com/file/d/1GN8RPVs76KPL1YkAChIimTm-vP0EznWm/view?usp=share_link
