### ISSUE TITLE
Formulário de solicitação de auxílio financeiro

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#7]
Criar formulário para solicitação de auxílio financeiro para participação da Python Brasil 2022, a partir da descrição resultante da #4 e critérios definidos em #3

**Comment by cecivieira** [comment]
Rascunho do formulário:
https://docs.google.com/document/d/1Z2k60hZKxkqfhX9TwB5kb4uZ1Q_Mfb7_b9uv5gJ8W1E/edit?usp=sharing

**Comment by alynnefs** [comment]
@cecivieira adicionei em uma parte separada as perguntas que foram feitas na última campanha das PyLadies

**Comment by cecivieira** [comment]
Formulário:
https://docs.google.com/forms/d/1M2ygpyETPeQIukYqZ3UL6fqq77dQT5YO0-i6OFRQuX8/edit

**Comment by cecivieira** [comment]
Prazo limite para alteração no formulário: 20 ago. 2022

**Comment by cecivieira** [comment]
@lipemorais fiz algumas modificações diretamente no formulário e adicionei uma mensagem automática de confirmação a ser enviada por e-mail.

@alynnefs tem uns comentários no rascunho. Dá uma olhada e vê se faz sentido transporta mais alguma pergunta do rascunho para o formulário.

**Comment by lipemorais** [comment]
Beleza, olho amanhã de manhã com calma. Por que hoje, só amanhã.

**Comment by lipemorais** [comment]
Olhando aqui novamente, o formulário. Não consigo pensar em nada que esteja faltando. Me parece pronto.

**Comment by julianyraiol** [comment]
Achei que ficou bem legal! cc: @wasp-lahis
