### ISSUE TITLE
Criar arte de divulgação

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2022-bolsa-viagem#9]
Criar arte para divulgação do programa de bolsa nas redes sociais da PyBR 2022.

**Comment by cecivieira** [comment]
Arte:
https://www.canva.com/design/DAFJ9iKEjOI/Lzz1B_yDHRoJAzcPYM68HA/edit?utm_content=DAFJ9iKEjOI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by cecivieira** [comment]
Sugestão de legenda:

Esse ano a PyLadies Brasil, AfroPython e Organização da Python Brasil promove o programa de bolsa de auxílio financeiro, que tem como objetivo apoiar a participação de grupos historicamente sub representados nas edições presenciais do evento  e ministrantes de atividades (palestras, tutoriais e sprints). O público alvo são pessoas, residentes em território nacional, que necessitam de apoio financeiro para comparecer ao evento e que de outra maneira não poderiam participar.

As solicitações devem ser enviadas entre 21 ago. e 03 set. através do formulário LINK .

Leia a descrição detalhada do programa em LINK.

**Comment by lipemorais** [comment]
Considero essa issue encerrada.

**Comment by cecivieira** [comment]
Solicitada divulgação à Org. PyBR2022:
https://github.com/pythonbrasil/pybr2022-org/issues/267
